<?php

declare(strict_types=1);

/**
 * Orangescrum Community Edition
 *
 * Copyright (c) 2026 Andolasoft Inc.
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License
 * for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

namespace App\Command;

use Cake\Command\Command;
use Cake\Console\Arguments;
use Cake\Console\ConsoleIo;
use Cake\Console\ConsoleOptionParser;
use Cake\Core\Plugin;
use Cake\Datasource\ConnectionManager;

/**
 * Finalize a MySQL -> PostgreSQL migration (Upgrade Guide phase 7).
 *
 * Devops-only, idempotent. Run AFTER pgloader has copied the MySQL data into the
 * PostgreSQL `public` schema. Order matters:
 *
 *   1. pg_config_1.sql        identity columns -> GENERATED BY DEFAULT
 *   2. gap DDL (updates.sql)  type coercions + columns pgloader could not infer
 *   3. plugin migrations      create PG-only plugin tables absent from MySQL
 *   4. pg_config_2.sql        reset every sequence to MAX(id)+1
 *   5. stamp phinxlog         mark main + plugin migrations as already applied
 *
 * Replaces the removed CopyOldDbCommand. Safe to re-run.
 */
class FinalizeMigrationCommand extends Command
{
    public function buildOptionParser(ConsoleOptionParser $parser): ConsoleOptionParser
    {
        $parser = parent::buildOptionParser($parser);
        $parser
            ->setDescription('Finalize a pgloader MySQL->Postgres migration (phase 7).')
            ->addOption('connection', ['help' => 'DB connection to use', 'default' => 'default'])
            ->addOption('reference', [
                'short' => 'r',
                'help' => 'Canonical reference DB — if set, reconcile schema via fill_schema_gaps',
            ])
            ->addOption('skip-plugin-migrations', [
                'help' => 'Do not run PG-only plugin migrations',
                'boolean' => true,
                'default' => false,
            ])
            ->addOption('skip-stamp', [
                'help' => 'Do not mark_migrated the phinxlog tables',
                'boolean' => true,
                'default' => false,
            ]);

        return $parser;
    }

    public function execute(Arguments $args, ConsoleIo $io): ?int
    {
        $connectionName = (string)$args->getOption('connection');

        $io->hr();
        $io->out('<info>Phase 7 — finalize MySQL -> PostgreSQL migration</info>');
        $io->hr();

        $this->runSqlFile($io, $connectionName, 'pg_config_1.sql', 'Step 1: identity columns -> GENERATED BY DEFAULT');
        $this->runSqlFile($io, $connectionName, 'updates.sql', 'Step 2: gap DDL (type coercions)');

        // Step 2b: reference-driven reconciliation (missing tables/columns + type
        // mismatches) — the deterministic gap-filler. Preferred over relying on
        // plugin migrations to create the newer-feature tables.
        $reference = $args->getOption('reference');
        if ($reference) {
            $io->out("  Step 2b: reconciling schema against reference '{$reference}'");
            $this->runShellCommand("php ./bin/cake.php fill_schema_gaps --reference " . escapeshellarg((string)$reference), $io);
        }

        if (!$args->getOption('skip-plugin-migrations') && !$reference) {
            $this->runPluginMigrations($io);
        }

        $this->runSqlFile($io, $connectionName, 'pg_config_2.sql', 'Step 4: reset sequences to MAX(id)+1');

        if (!$args->getOption('skip-stamp')) {
            $this->stampPhinxlog($io);
        }

        $io->hr();
        $io->out('<success>Finalize complete.</success>');
        $io->hr();

        return static::CODE_SUCCESS;
    }

    /**
     * Execute a config/schema/*.sql file as a single batch. Idempotent SQL only.
     */
    protected function runSqlFile(ConsoleIo $io, string $connectionName, string $file, string $label): void
    {
        $io->out("  {$label}");
        $path = CONFIG . 'schema' . DS . $file;

        if (!is_file($path)) {
            $io->warning("    skipped — {$file} not found");

            return;
        }

        $sql = trim((string)file_get_contents($path));
        if ($sql === '') {
            $io->warning("    skipped — {$file} empty");

            return;
        }

        $connection = ConnectionManager::get($connectionName);
        try {
            $connection->execute($sql);
            $io->out("    <success>✓</success> applied {$file}");
        } catch (\Throwable $e) {
            // Statement-level fallback so one already-applied ALTER does not abort
            // the whole file on a re-run.
            $io->out("    batch failed, retrying statement-by-statement ({$file})");
            $applied = 0;
            $skipped = 0;
            foreach ($this->splitStatements($sql) as $stmt) {
                try {
                    $connection->execute($stmt);
                    $applied++;
                } catch (\Throwable $inner) {
                    $skipped++;
                }
            }
            $io->out("    <success>✓</success> {$file}: {$applied} applied, {$skipped} already-applied/skipped");
        }
    }

    /**
     * @return string[]
     */
    protected function splitStatements(string $sql): array
    {
        $noComments = preg_replace('/^\s*--.*$/m', '', $sql);

        return array_values(array_filter(array_map('trim', explode(';', (string)$noComments)), fn($s) => $s !== ''));
    }

    protected function runPluginMigrations(ConsoleIo $io): void
    {
        $io->out('  Step 3: PG-only plugin migrations');
        $plugins = array_filter(Plugin::loaded(), fn($p) => is_dir(ROOT . DS . 'plugins' . DS . $p . DS . 'config' . DS . 'Migrations'));
        foreach ($plugins as $plugin) {
            $io->out("    migrations migrate -p {$plugin}");
            $this->runShellCommand("php ./bin/cake.php migrations migrate -p {$plugin}", $io);
        }
        if (!$plugins) {
            $io->out('    (no plugins with migrations)');
        }
    }

    protected function stampPhinxlog(ConsoleIo $io): void
    {
        $io->out('  Step 5: stamp phinxlog (mark_migrated)');
        $this->runShellCommand('php ./bin/cake.php migrations mark_migrated', $io);
        $plugins = array_filter(Plugin::loaded(), fn($p) => is_dir(ROOT . DS . 'plugins' . DS . $p . DS . 'config' . DS . 'Migrations'));
        foreach ($plugins as $plugin) {
            $this->runShellCommand("php ./bin/cake.php migrations mark_migrated -p {$plugin}", $io);
        }
    }

    protected function runShellCommand(string $command, ConsoleIo $io): int
    {
        $descriptorSpec = [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'w']];
        $process = proc_open($command, $descriptorSpec, $pipes, ROOT);
        if (!is_resource($process)) {
            $io->warning("    could not start: {$command}");

            return 1;
        }
        fclose($pipes[0]);
        $out = stream_get_contents($pipes[1]);
        $err = stream_get_contents($pipes[2]);
        fclose($pipes[1]);
        fclose($pipes[2]);
        $code = proc_close($process);
        foreach (preg_split('/\R/', trim($out . "\n" . $err)) as $line) {
            if (trim($line) !== '') {
                $io->out('      ' . $line);
            }
        }

        return $code;
    }
}
