<?php

use Migrations\AbstractSeed;

class CustomStatusesSeeder extends AbstractSeed
{
    public function run(): void
    {
        $data = [
            0 =>
                [
                    'id' => 20,
                    'company_id' => 0,
                    'name' => 'New',
                    'progress' => 0,
                    'color' => 'F08E83',
                    'status_master_id' => 1,
                    'status_group_id' => 1,
                    'seq' => 1,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            1 =>
                [
                    'id' => 21,
                    'company_id' => 0,
                    'name' => 'In Progress',
                    'progress' => 0,
                    'color' => '6BA8DE',
                    'status_master_id' => 2,
                    'status_group_id' => 1,
                    'seq' => 2,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            2 =>
                [
                    'id' => 22,
                    'company_id' => 0,
                    'name' => 'Resolve',
                    'progress' => 100,
                    'color' => 'FAB858',
                    'status_master_id' => 2,
                    'status_group_id' => 1,
                    'seq' => 3,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            3 =>
                [
                    'id' => 23,
                    'company_id' => 0,
                    'name' => 'Close',
                    'progress' => 100,
                    'color' => '72CA8D',
                    'status_master_id' => 3,
                    'status_group_id' => 1,
                    'seq' => 4,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            4 =>
                [
                    'id' => 24,
                    'company_id' => 0,
                    'name' => 'Backlog',
                    'progress' => 0,
                    'color' => 'F08E83',
                    'status_master_id' => 1,
                    'status_group_id' => 2,
                    'seq' => 1,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            5 =>
                [
                    'id' => 25,
                    'company_id' => 0,
                    'name' => 'Ready',
                    'progress' => 0,
                    'color' => 'C55447',
                    'status_master_id' => 2,
                    'status_group_id' => 2,
                    'seq' => 2,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            6 =>
                [
                    'id' => 26,
                    'company_id' => 0,
                    'name' => 'In Progress',
                    'progress' => 30,
                    'color' => '6BA8DE',
                    'status_master_id' => 2,
                    'status_group_id' => 2,
                    'seq' => 3,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            7 =>
                [
                    'id' => 27,
                    'company_id' => 0,
                    'name' => 'Done',
                    'progress' => 100,
                    'color' => '72CA8D',
                    'status_master_id' => 3,
                    'status_group_id' => 2,
                    'seq' => 4,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            8 =>
                [
                    'id' => 28,
                    'company_id' => 0,
                    'name' => 'Open',
                    'progress' => 0,
                    'color' => 'F08E83',
                    'status_master_id' => 1,
                    'status_group_id' => 3,
                    'seq' => 1,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            9 =>
                [
                    'id' => 29,
                    'company_id' => 0,
                    'name' => 'In Progress',
                    'progress' => 30,
                    'color' => '6BA8DE',
                    'status_master_id' => 2,
                    'status_group_id' => 3,
                    'seq' => 2,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            10 =>
                [
                    'id' => 30,
                    'company_id' => 0,
                    'name' => 'Approved',
                    'progress' => 100,
                    'color' => '72CA8D',
                    'status_master_id' => 3,
                    'status_group_id' => 3,
                    'seq' => 5,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            11 =>
                [
                    'id' => 31,
                    'company_id' => 0,
                    'name' => 'Cancelled',
                    'progress' => 50,
                    'color' => 'C75863',
                    'status_master_id' => 2,
                    'status_group_id' => 3,
                    'seq' => 3,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            12 =>
                [
                    'id' => 32,
                    'company_id' => 0,
                    'name' => 'Rejected',
                    'progress' => 0,
                    'color' => 'E42135',
                    'status_master_id' => 2,
                    'status_group_id' => 3,
                    'seq' => 4,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            13 =>
                [
                    'id' => 33,
                    'company_id' => 0,
                    'name' => 'To Do',
                    'progress' => 0,
                    'color' => 'F08E83',
                    'status_master_id' => 1,
                    'status_group_id' => 4,
                    'seq' => 1,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            14 =>
                [
                    'id' => 34,
                    'company_id' => 0,
                    'name' => 'Done',
                    'progress' => 100,
                    'color' => '72CA8D',
                    'status_master_id' => 3,
                    'status_group_id' => 4,
                    'seq' => 2,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            15 =>
                [
                    'id' => 35,
                    'company_id' => 0,
                    'name' => 'Application',
                    'progress' => 0,
                    'color' => 'F08E83',
                    'status_master_id' => 1,
                    'status_group_id' => 5,
                    'seq' => 1,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            16 =>
                [
                    'id' => 36,
                    'company_id' => 0,
                    'name' => 'Screening',
                    'progress' => 10,
                    'color' => '6BA8DE',
                    'status_master_id' => 2,
                    'status_group_id' => 5,
                    'seq' => 2,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            17 =>
                [
                    'id' => 37,
                    'company_id' => 0,
                    'name' => 'Interviewing',
                    'progress' => 30,
                    'color' => '0F69A9',
                    'status_master_id' => 2,
                    'status_group_id' => 5,
                    'seq' => 3,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            18 =>
                [
                    'id' => 38,
                    'company_id' => 0,
                    'name' => 'Interview offer',
                    'progress' => 50,
                    'color' => '00F3FF',
                    'status_master_id' => 2,
                    'status_group_id' => 5,
                    'seq' => 4,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            19 =>
                [
                    'id' => 39,
                    'company_id' => 0,
                    'name' => 'Offer discussion',
                    'progress' => 70,
                    'color' => '2EC74A',
                    'status_master_id' => 2,
                    'status_group_id' => 5,
                    'seq' => 5,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            20 =>
                [
                    'id' => 40,
                    'company_id' => 0,
                    'name' => 'Accepted',
                    'progress' => 100,
                    'color' => '045E1F',
                    'status_master_id' => 3,
                    'status_group_id' => 5,
                    'seq' => 7,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            21 =>
                [
                    'id' => 41,
                    'company_id' => 0,
                    'name' => 'Rejected',
                    'progress' => 100,
                    'color' => 'FF0000',
                    'status_master_id' => 3,
                    'status_group_id' => 5,
                    'seq' => 6,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            22 =>
                [
                    'id' => 42,
                    'company_id' => 0,
                    'name' => 'Requested',
                    'progress' => 0,
                    'color' => 'F08E83',
                    'status_master_id' => 1,
                    'status_group_id' => 6,
                    'seq' => 1,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            23 =>
                [
                    'id' => 43,
                    'company_id' => 0,
                    'name' => 'In Review',
                    'progress' => 30,
                    'color' => '6BA8DE',
                    'status_master_id' => 2,
                    'status_group_id' => 6,
                    'seq' => 2,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
            24 =>
                [
                    'id' => 44,
                    'company_id' => 0,
                    'name' => 'Approved',
                    'progress' => 100,
                    'color' => '50B36E',
                    'status_master_id' => 3,
                    'status_group_id' => 6,
                    'seq' => 3,
                    'created' => '2019-11-25 00:00:00',
                    'modified' => '2019-11-25 00:00:00',
                ],
        ];
        $this->table('custom_statuses')->insert($data)->save();
    }
}
