<?php
/**
 * Email template manifest.
 *
 * Each entry declares:
 *   - shell           : layout file under templates/email/html/shells/<shell>.php
 *   - accent_color    : header bar + button color for the shell
 *   - regions         : named editable fields the admin sees; each region has a
 *                       label, type (text|textarea), and a `default` containing
 *                       inline HTML + {{ tokens }}
 *   - tokens          : whitelisted {{ tokens }} the admin may insert into any region
 *   - default_subject : subject line with {{ tokens }}
 *
 * Region values store raw HTML — DO escape downstream user input that flows in
 * through tokens (default = scalar tokens get htmlspecialchars; raw=true skips).
 */

$_companyNotificationFooter = 'You received this because you have an account on {{ companyName }}. If you have questions, reply to this email.';

return [
    'EmailTemplating' => [
        'templates' => [
            // -----------------------------------------------------------
            // Layout — outer chrome wrapped around every email body when the
            // matching include switch is on in Common Settings. Each is an
            // editable template like any other; the shell `fragment` just
            // emits the resolved `body` region verbatim, no card wrapper.
            // -----------------------------------------------------------
            'email_header' => [
                'label' => 'Email Header',
                'category' => 'Layout',
                'description' => 'Logo banner rendered above every email when "Include default email header" is on.',
                'plugin' => null,
                'shell' => 'email_header_layout',
                'accent_color' => '#FFFFFF',
                'regions' => [
                    'logo_url' => ['label' => 'Logo image URL', 'type' => 'text', 'default' => '{{ baseUrl }}/img/logo/orangescrum-100-100.png'],
                    'logo_alt' => ['label' => 'Logo alt text', 'type' => 'text', 'default' => '{{ companyName }}'],
                    'home_url' => ['label' => 'Link target (when reader clicks the logo)', 'type' => 'text', 'default' => '{{ baseUrl }}/'],
                    'background_color' => ['label' => 'Background color', 'type' => 'text', 'default' => '#FFFFFF'],
                ],
                'tokens' => [
                    'companyName' => ['label' => 'Company name', 'sample' => 'Orangescrum'],
                    'baseUrl' => ['label' => 'Base URL', 'sample' => 'https://example.com'],
                ],
                'default_subject' => '',
            ],
            'email_footer' => [
                'label' => 'Email Footer',
                'category' => 'Layout',
                'description' => 'Links, address, and unsubscribe note rendered below every email when "Include default email footer" is on.',
                'plugin' => null,
                'shell' => 'email_footer_layout',
                'accent_color' => '#F9FAFB',
                'regions' => [
                    'blog_url' => ['label' => 'Blog URL (leave empty to hide)', 'type' => 'text', 'default' => 'https://blog.orangescrum.com/'],
                    'help_url' => ['label' => 'Help URL (leave empty to hide)', 'type' => 'text', 'default' => 'https://www.orangescrum.com/help'],
                    'about_url' => ['label' => 'About URL (leave empty to hide)', 'type' => 'text', 'default' => 'https://www.orangescrum.com/about-us'],
                    'twitter_url' => ['label' => 'Twitter URL (leave empty to hide)', 'type' => 'text', 'default' => ''],
                    'facebook_url' => ['label' => 'Facebook URL (leave empty to hide)', 'type' => 'text', 'default' => ''],
                    'copyright_text' => ['label' => 'Copyright line', 'type' => 'text', 'default' => '© {{ year }} {{ companyName }}. All rights reserved.'],
                    'address_text' => ['label' => 'Company address', 'type' => 'text', 'default' => '{{ companyAddress }}'],
                    'unsubscribe_text' => ['label' => 'Unsubscribe note', 'type' => 'textarea', 'default' => 'You received this message because you are a {{ companyName }} customer.'],
                    'unsubscribe_link_label' => ['label' => 'Unsubscribe link label (leave empty to hide)', 'type' => 'text', 'default' => 'Manage email preferences'],
                    'unsubscribe_link_url' => ['label' => 'Unsubscribe link URL', 'type' => 'text', 'default' => '{{ baseUrl }}/users/profile'],
                    'background_color' => ['label' => 'Background color', 'type' => 'text', 'default' => '#F9FAFB'],
                ],
                'tokens' => [
                    'companyName' => ['label' => 'Company name', 'sample' => 'Orangescrum'],
                    'companyAddress' => ['label' => 'Company address', 'sample' => '2059 Camden Ave. #118, San Jose, CA 95124, USA'],
                    'year' => ['label' => 'Current year', 'sample' => date('Y')],
                    'baseUrl' => ['label' => 'Base URL', 'sample' => 'https://example.com'],
                ],
                'default_subject' => '',
            ],

            // -----------------------------------------------------------
            // Auth
            // -----------------------------------------------------------
            'registration_welcome' => [
                'label' => 'Registration - Welcome',
                'category' => 'Auth',
                'description' => 'Sent after a user activates their account.',
                'plugin' => null,
                'shell' => 'notification',
                'accent_color' => '#2E7D32',
                'regions' => [
                    'heading' => ['label' => 'Heading', 'type' => 'text', 'default' => 'Welcome to {{ companyName }}'],
                    'greeting' => ['label' => 'Greeting', 'type' => 'text', 'default' => 'Dear {{ userName }},'],
                    'body' => ['label' => 'Body', 'type' => 'textarea', 'default' => 'Your account on <strong>{{ companyName }} Project Management</strong> has been activated. You can now sign in and start using the platform.'],
                    'cta_label' => ['label' => 'Button label', 'type' => 'text', 'default' => 'Sign in to your account'],
                    'cta_url' => ['label' => 'Button URL', 'type' => 'text', 'default' => '{{ ctaUrl }}'],
                    'signoff' => ['label' => 'Sign-off', 'type' => 'signoff', 'default' => 'Thanks &amp; Regards,<br><strong>The {{ companyName }} Team</strong>'],
                    'footer_note' => ['label' => 'Footer note', 'type' => 'textarea', 'default' => 'If you need any help, please write to <a href="mailto:{{ supportEmail }}">{{ supportEmail }}</a>.'],
                ],
                'metadata_rows' => [
                    ['label' => 'Account', 'value' => '{{ accountName }}'],
                    ['label' => 'Company', 'value' => '{{ companyName }}'],
                ],
                'tokens' => [
                    'userName' => ['label' => 'User name', 'sample' => 'John Doe'],
                    'companyName' => ['label' => 'Company name', 'sample' => 'Orangescrum'],
                    'loginUrl' => ['label' => 'Sign-in URL', 'sample' => 'https://example.com/login'],
                    'accountName' => ['label' => 'Account holder / login account name', 'sample' => 'alex.smith'],
                    'ctaUrl' => ['label' => 'Primary CTA hyperlink target', 'sample' => 'https://example.com/login'],
                    'supportEmail' => ['label' => 'Support / help mailto address', 'sample' => 'support@orangescrum.com'],
                ],
                'default_subject' => 'Welcome to {{ companyName }} - your account is active',
            ],
            'forgot_password' => [
                'label' => 'Forgot Password',
                'category' => 'Auth',
                'description' => 'Sent when a user requests a password reset.',
                'plugin' => null,
                'shell' => 'notification',
                'accent_color' => '#FB8C00',
                'regions' => [
                    'heading' => ['label' => 'Heading', 'type' => 'text', 'default' => 'Reset your password'],
                    'greeting' => ['label' => 'Greeting', 'type' => 'text', 'default' => 'Dear {{ userName }},'],
                    'body' => ['label' => 'Body', 'type' => 'textarea', 'default' => 'We received a request to reset the password for your {{ companyName }} account (<strong>{{ actorName }}</strong>). Click the button below to choose a new password. If you did not make this request you can safely ignore this email.'],
                    'cta_label' => ['label' => 'Button label', 'type' => 'text', 'default' => 'Reset password'],
                    'cta_url' => ['label' => 'Button URL', 'type' => 'text', 'default' => '{{ ctaUrl }}'],
                    'signoff' => ['label' => 'Sign-off', 'type' => 'signoff', 'default' => 'Thanks &amp; Regards,<br><strong>The {{ companyName }} Team</strong>'],
                    'footer_note' => ['label' => 'Footer note', 'type' => 'textarea', 'default' => 'This link expires in a short time for your security. If you have trouble, please write to <a href="mailto:{{ supportEmail }}">{{ supportEmail }}</a>.'],
                ],
                'tokens' => [
                    'userName' => ['label' => 'User name', 'sample' => 'John Doe'],
                    'resetUrl' => ['label' => 'Reset URL', 'sample' => 'https://example.com/reset/abc'],
                    'companyName' => ['label' => 'Company name', 'sample' => 'Orangescrum'],
                    'actorName' => ['label' => 'User who triggered the event', 'sample' => 'John Doe'],
                    'ctaUrl' => ['label' => 'Primary CTA hyperlink target', 'sample' => 'https://example.com/reset/abc'],
                    'supportEmail' => ['label' => 'Support / help mailto address', 'sample' => 'support@orangescrum.com'],
                ],
                'default_subject' => 'Reset your {{ companyName }} password',
            ],
            'invite_user' => [
                'label' => 'Invite User',
                'category' => 'Auth',
                'description' => 'Sent when an admin invites a new user.',
                'plugin' => null,
                'shell' => 'notification',
                'accent_color' => '#FB8C00',
                'regions' => [
                    'heading' => ['label' => 'Heading', 'type' => 'text', 'default' => "You're invited to {{ companyName }}"],
                    'greeting' => ['label' => 'Greeting', 'type' => 'text', 'default' => 'Dear {{ userName }},'],
                    'body' => ['label' => 'Body', 'type' => 'textarea', 'default' => 'You have been invited to join the {{ companyName }} Project Management workspace. Click the button below to set up your account and start collaborating.'],
                    'cta_label' => ['label' => 'Button label', 'type' => 'text', 'default' => 'Accept invitation'],
                    'cta_url' => ['label' => 'Button URL', 'type' => 'text', 'default' => '{{ ctaUrl }}'],
                    'signoff' => ['label' => 'Sign-off', 'type' => 'signoff', 'default' => 'Thanks &amp; Regards,<br><strong>The {{ companyName }} Team</strong>'],
                    'footer_note' => ['label' => 'Footer note', 'type' => 'textarea', 'default' => 'If you have any questions please write to <a href="mailto:{{ supportEmail }}">{{ supportEmail }}</a>.'],
                ],
                'tokens' => [
                    'inviteeName' => ['label' => 'Invited user name', 'sample' => 'John Doe'],
                    'inviterName' => ['label' => 'Inviter name', 'sample' => 'Jane Doe'],
                    'companyName' => ['label' => 'Company name', 'sample' => 'Orangescrum'],
                    'inviteUrl' => ['label' => 'Accept-invite URL', 'sample' => 'https://example.com/invite/xyz'],
                    'userName' => ['label' => "Recipient's display name", 'sample' => 'John Doe'],
                    'ctaUrl' => ['label' => 'Primary CTA hyperlink target', 'sample' => 'https://example.com/invite/xyz'],
                    'supportEmail' => ['label' => 'Support / help mailto address', 'sample' => 'support@orangescrum.com'],
                ],
                'default_subject' => "You're invited to {{ companyName }} by {{ inviterName }}",
            ],

            // -----------------------------------------------------------
            // Projects
            // -----------------------------------------------------------
            'project_add' => [
                'label' => 'Project Added (Project Member)',
                'category' => 'Projects',
                'description' => 'Sent when a user is added to a project.',
                'plugin' => null,
                'shell' => 'notification',
                'accent_color' => '#0277BD',
                'regions' => [
                    'heading' => ['label' => 'Heading', 'type' => 'text', 'default' => 'Added to a project'],
                    'greeting' => ['label' => 'Greeting', 'type' => 'text', 'default' => 'Dear {{ userName }},'],
                    'body' => ['label' => 'Body', 'type' => 'textarea', 'default' => '<strong>{{ actorName }}</strong> has added you to the project <strong>{{ projectName }}</strong> on {{ companyName }}.'],
                    'cta_label' => ['label' => 'Button label', 'type' => 'text', 'default' => 'Open project'],
                    'cta_url' => ['label' => 'Button URL', 'type' => 'text', 'default' => '{{ ctaUrl }}'],
                    'signoff' => ['label' => 'Sign-off', 'type' => 'signoff', 'default' => 'Thanks &amp; Regards,<br><strong>The {{ companyName }} Team</strong>'],
                    'footer_note' => ['label' => 'Footer note', 'type' => 'textarea', 'default' => $_companyNotificationFooter],
                ],
                'tokens' => [
                    'recipientName' => ['label' => 'Recipient name', 'sample' => 'John Doe'],
                    'addedByName' => ['label' => 'Added by', 'sample' => 'Jane Doe'],
                    'projName' => ['label' => 'Project name', 'sample' => 'Sample Project'],
                    'projUrl' => ['label' => 'Project URL', 'sample' => 'https://example.com/p/cpr'],
                    'companyName' => ['label' => 'Company name', 'sample' => 'Orangescrum'],
                    'userName' => ['label' => "Recipient's display name", 'sample' => 'John Doe'],
                    'actorName' => ['label' => 'User who triggered the event', 'sample' => 'Jane Doe'],
                    'projectName' => ['label' => 'Project display name', 'sample' => 'Sample Project'],
                    'ctaUrl' => ['label' => 'Primary CTA hyperlink target', 'sample' => 'https://example.com/p/cpr'],
                ],
                'default_subject' => 'You have been added to {{ projectName }}',
            ],
            'project_note' => [
                'label' => 'Project Note - Added / Updated',
                'category' => 'Projects',
                'description' => 'Sent when a project note is added or updated.',
                'plugin' => null,
                'shell' => 'notification',
                'accent_color' => '#0277BD',
                'regions' => [
                    'heading' => ['label' => 'Heading', 'type' => 'text', 'default' => 'Project note updated'],
                    'greeting' => ['label' => 'Greeting', 'type' => 'text', 'default' => 'Dear {{ userName }},'],
                    'body' => ['label' => 'Body', 'type' => 'textarea', 'default' => 'A project note has been <strong>{{ noteAction }}</strong> on the project <strong>{{ projectName }}</strong>.<br><br>{{ noteBody }}'],
                    'cta_label' => ['label' => 'Button label', 'type' => 'text', 'default' => 'Open project'],
                    'cta_url' => ['label' => 'Button URL', 'type' => 'text', 'default' => '{{ ctaUrl }}'],
                    'signoff' => ['label' => 'Sign-off', 'type' => 'signoff', 'default' => 'Thanks &amp; Regards,<br><strong>The {{ companyName }} Team</strong>'],
                    'footer_note' => ['label' => 'Footer note', 'type' => 'textarea', 'default' => $_companyNotificationFooter],
                ],
                'tokens' => [
                    'recipientName' => ['label' => 'Recipient name', 'sample' => 'John Doe'],
                    'actorName' => ['label' => 'User who triggered the event', 'sample' => 'John Doe'],
                    'projName' => ['label' => 'Project name', 'sample' => 'Customer Portal Redesign'],
                    'projectName' => ['label' => 'Project display name', 'sample' => 'Customer Portal Redesign'],
                    'noteAction' => ['label' => "Action verb on the note ('added' / 'updated')", 'sample' => 'added'],
                    'noteBody' => ['label' => 'Project-note body text (raw HTML allowed)', 'sample' => '<strong>Release notes:</strong> v2.4 ships Monday; please sign off on the changelog by EOD.', 'raw' => true],
                    'companyName' => ['label' => 'Company name', 'sample' => 'Orangescrum'],
                    'userName' => ['label' => "Recipient's display name", 'sample' => 'John Doe'],
                    'ctaUrl' => ['label' => 'Primary CTA hyperlink target', 'sample' => 'https://example.com/p/customer-portal'],
                ],
                'default_subject' => 'Project note added on &quot;{{ projectName }}&quot;',
            ],
            // -----------------------------------------------------------
            // Workflow
            // -----------------------------------------------------------
            'workflow_action' => [
                'label' => 'Workflow Action',
                'category' => 'Workflow',
                'description' => 'Sent on workflow state transition.',
                'plugin' => null,
                'shell' => 'task_activity',
                'accent_color' => '#FB8C00',
                'regions' => [
                    'heading' => ['label' => 'Heading', 'type' => 'text', 'default' => 'Workflow update'],
                    'greeting' => ['label' => 'Greeting', 'type' => 'text', 'default' => 'Dear {{ userName }},'],
                    'intro' => ['label' => 'Intro line', 'type' => 'textarea', 'default' => '<strong>{{ actorName }}</strong> triggered a workflow action on a task you are working on.'],
                    'comment_label' => ['label' => 'Message label', 'type' => 'text', 'default' => 'Message'],
                    'cta_label' => ['label' => 'Button label', 'type' => 'text', 'default' => 'View task'],
                    'cta_url' => ['label' => 'Button URL', 'type' => 'text', 'default' => '/dashboard/#details/{{ case_uniq_id }}'],
                    'signoff' => ['label' => 'Sign-off', 'type' => 'signoff', 'default' => 'Thanks &amp; Regards,<br><strong>The {{ companyName }} Team</strong>'],
                    'footer_note' => ['label' => 'Footer note', 'type' => 'textarea', 'default' => $_companyNotificationFooter],
                ],
                'tokens' => [
                    'recipientName' => ['label' => 'Recipient name', 'sample' => 'John Doe'],
                    'actorName' => ['label' => 'Acting user', 'sample' => 'Jane Doe'],
                    'docTitle' => ['label' => 'Document / item title', 'sample' => 'Sample Document'],
                    'workflowName' => ['label' => 'Workflow name', 'sample' => 'Sample Workflow'],
                    'message_text' => ['label' => 'Workflow message', 'sample' => 'Sample workflow message.', 'raw' => true],
                    'case_title' => ['label' => 'Task title', 'sample' => 'Sample task title'],
                    'case_no' => ['label' => 'Task number', 'sample' => 'TSK-04-0008'],
                    'case_uniq_id' => ['label' => 'Task UUID', 'sample' => '7a1b2c3d-4e5f-6789-abcd-ef0123456789'],
                    'projName' => ['label' => 'Project name', 'sample' => 'Sample Project'],
                    'cseTyp' => ['label' => 'Task type', 'sample' => 'Story'],
                    'priRity' => ['label' => 'Priority (raw HTML allowed)', 'sample' => 'P2 - High', 'raw' => true],
                    'respond' => ['label' => 'Workflow message body (raw HTML allowed)', 'sample' => 'Sample workflow message.', 'raw' => true],
                    'statusBadge' => ['label' => 'Status badge (raw HTML)', 'sample' => '', 'raw' => true],
                    'companyName' => ['label' => 'Company name', 'sample' => 'Orangescrum'],
                    'userName' => ['label' => "Recipient's display name", 'sample' => 'John Doe'],
                    'ctaUrl' => ['label' => 'Primary CTA hyperlink target', 'sample' => 'https://example.com/'],
                ],
                'default_subject' => 'Workflow update on {{ companyName }}',
            ],

            // -----------------------------------------------------------
            // Tasks (no shell yet — these have a richer task-activity layout
            // pending its own shell). For now they expose raw HTML editing.
            // -----------------------------------------------------------
            'task_comment' => [
                'label' => 'Task - Comment',
                'category' => 'Tasks',
                'description' => 'Sent when someone comments / replies on a task you are working on.',
                'plugin' => null,
                'shell' => 'task_activity',
                'accent_color' => '#0277BD',
                'regions' => [
                    'heading' => ['label' => 'Heading', 'type' => 'text', 'default' => 'New comment on a task'],
                    'intro' => ['label' => 'Intro line', 'type' => 'textarea', 'default' => '<strong>{{ actorFullName }}</strong> commented on a task you are working on.'],
                    'comment_label' => ['label' => 'Comment label (optional)', 'type' => 'text', 'default' => 'Comment'],
                    'cta_label' => ['label' => 'Button label', 'type' => 'text', 'default' => 'View task'],
                    'cta_url' => ['label' => 'Button URL', 'type' => 'text', 'default' => '/dashboard/#details/{{ case_uniq_id }}'],
                    'signoff' => ['label' => 'Sign-off', 'type' => 'signoff', 'default' => 'Thanks &amp; Regards,<br><strong>The {{ companyName }} Team</strong>'],
                    'footer_note' => ['label' => 'Footer note', 'type' => 'textarea', 'default' => "Don't want these emails? Ask your project admin to turn off email notifications for this project."],
                ],
                'tokens' => [
                    'actorName' => ['label' => 'Commenter name', 'sample' => 'Jane Doe'],
                    'actorFullName' => ['label' => 'Commenter full name', 'sample' => 'Jane Doe'],
                    'actorEmail' => ['label' => 'Commenter email', 'sample' => 'jane@example.com'],
                    'recipientName' => ['label' => 'Recipient name', 'sample' => 'John Doe'],
                    'case_title' => ['label' => 'Task title', 'sample' => 'Sample task title'],
                    'case_no' => ['label' => 'Task number', 'sample' => 'TSK-04-0008'],
                    'case_uniq_id' => ['label' => 'Task UUID', 'sample' => '7a1b2c3d-4e5f-6789-abcd-ef0123456789'],
                    'projName' => ['label' => 'Project name', 'sample' => 'Sample Project'],
                    'cseTyp' => ['label' => 'Task type', 'sample' => 'Story'],
                    'priRity' => ['label' => 'Priority (raw HTML allowed)', 'sample' => 'P2 - High', 'raw' => true],
                    'respond' => ['label' => 'Comment body (raw HTML allowed)', 'sample' => 'Sample comment body.', 'raw' => true],
                    'statusBadge' => ['label' => 'Status badge (raw HTML)', 'sample' => '', 'raw' => true],
                    'attachments' => ['label' => 'Attachments list (raw HTML)', 'sample' => '<a href="#" style="color:#2489B3;">requirements.pdf</a>, <a href="#" style="color:#2489B3;">mockup.png</a>', 'raw' => true],
                    'assignmentLine' => ['label' => 'Assignment line (raw HTML)', 'sample' => '', 'raw' => true],
                    'companyName' => ['label' => 'Company name', 'sample' => 'Orangescrum'],
                    'projectName' => ['label' => 'Project display name', 'sample' => 'Sample Project'],
                    'taskTitle' => ['label' => 'Task title / summary', 'sample' => 'Sample task title'],
                    'taskNo' => ['label' => 'Task code', 'sample' => 'TSK-04-0008'],
                    'taskType' => ['label' => 'Task type label', 'sample' => 'Story'],
                    'priorityLabel' => ['label' => 'Priority chip text', 'sample' => 'P2 - High'],
                    'commentBody' => ['label' => 'User-typed comment / note body', 'sample' => 'Sample comment body.', 'raw' => true],
                    'attachmentsList' => ['label' => 'Rendered list of attachment links', 'sample' => '<a href="#" style="color:#2489B3;">requirements.pdf</a>, <a href="#" style="color:#2489B3;">mockup.png</a>', 'raw' => true],
                    'ctaUrl' => ['label' => 'Primary CTA hyperlink target', 'sample' => 'https://example.com/task/TSK-04-0008'],
                ],
                'default_subject' => 'New comment on {{ projectName }} - {{ taskTitle }}',
            ],
            'task_mention' => [
                'label' => 'Task - Mention',
                'category' => 'Tasks',
                'description' => 'Sent when a user is @-mentioned in a task comment.',
                'plugin' => null,
                'shell' => 'task_activity',
                'accent_color' => '#6A1B9A',
                'regions' => [
                    'heading' => ['label' => 'Heading', 'type' => 'text', 'default' => 'You were mentioned on a task'],
                    'intro' => ['label' => 'Intro line', 'type' => 'textarea', 'default' => '<strong>{{ actorFullName }}</strong> mentioned you on a task. Please review the message below.'],
                    'comment_label' => ['label' => 'Comment label (optional)', 'type' => 'text', 'default' => 'Mention'],
                    'cta_label' => ['label' => 'Button label', 'type' => 'text', 'default' => 'View task'],
                    'cta_url' => ['label' => 'Button URL', 'type' => 'text', 'default' => '{{ ctaUrl }}'],
                    'signoff' => ['label' => 'Sign-off', 'type' => 'signoff', 'default' => 'Thanks &amp; Regards,<br><strong>The {{ companyName }} Team</strong>'],
                    'footer_note' => ['label' => 'Footer note', 'type' => 'textarea', 'default' => "Don't want these emails? Ask your project admin to turn off email notifications for this project."],
                ],
                'tokens' => [
                    'actorName' => ['label' => 'Mentioning user', 'sample' => 'Jane Doe'],
                    'actorFullName' => ['label' => 'Mentioning user full name', 'sample' => 'Jane Doe'],
                    'actorEmail' => ['label' => 'Mentioning user email', 'sample' => 'jane@example.com'],
                    'recipientName' => ['label' => 'Recipient name', 'sample' => 'John Doe'],
                    'case_title' => ['label' => 'Task title', 'sample' => 'Sample task title'],
                    'case_no' => ['label' => 'Task number', 'sample' => 'TSK-04-0012'],
                    'case_uniq_id' => ['label' => 'Task UUID', 'sample' => '7a1b2c3d-4e5f-6789-abcd-ef0123456789'],
                    'projName' => ['label' => 'Project name', 'sample' => 'Sample Project'],
                    'cseTyp' => ['label' => 'Task type', 'sample' => 'Story'],
                    'priRity' => ['label' => 'Priority (raw HTML allowed)', 'sample' => 'P2 - High', 'raw' => true],
                    'respond' => ['label' => 'Mention body (raw HTML allowed)', 'sample' => '@Alex please take a look when you can.', 'raw' => true],
                    'statusBadge' => ['label' => 'Status badge (raw HTML)', 'sample' => '', 'raw' => true],
                    'attachments' => ['label' => 'Attachments list (raw HTML)', 'sample' => '<a href="#" style="color:#2489B3;">requirements.pdf</a>, <a href="#" style="color:#2489B3;">mockup.png</a>', 'raw' => true],
                    'assignmentLine' => ['label' => 'Assignment line (raw HTML)', 'sample' => '', 'raw' => true],
                    'companyName' => ['label' => 'Company name', 'sample' => 'Orangescrum'],
                    'projectName' => ['label' => 'Project display name', 'sample' => 'Customer Portal Redesign'],
                    'taskTitle' => ['label' => 'Task title / summary', 'sample' => 'Customer Portal Redesign'],
                    'taskNo' => ['label' => 'Task code', 'sample' => 'TSK-04-0012'],
                    'taskType' => ['label' => 'Task type label', 'sample' => 'Story'],
                    'priorityLabel' => ['label' => 'Priority chip text', 'sample' => 'P2 - High'],
                    'commentBody' => ['label' => 'User-typed comment / mention body', 'sample' => '@Alex please take a look when you can.', 'raw' => true],
                    'mentionBody' => ['label' => 'Mention body (raw HTML allowed)', 'sample' => '@Alex please take a look when you can.', 'raw' => true],
                    'attachmentsList' => ['label' => 'Rendered list of attachment links', 'sample' => '<a href="#" style="color:#2489B3;">requirements.pdf</a>, <a href="#" style="color:#2489B3;">mockup.png</a>', 'raw' => true],
                    'ctaUrl' => ['label' => 'Primary CTA hyperlink target', 'sample' => 'https://example.com/task/TSK-04-0012'],
                ],
                'default_subject' => 'You were mentioned on {{ projectName }} - {{ taskTitle }}',
            ],
            'task_created' => [
                'label' => 'Task - Created',
                'category' => 'Tasks',
                'description' => 'Sent when a new task is created (e.g. to the assignee or project followers).',
                'plugin' => null,
                'shell' => 'task_activity',
                'accent_color' => '#2E7D32',
                'regions' => [
                    'heading' => ['label' => 'Heading', 'type' => 'text', 'default' => 'New task created'],
                    'intro' => ['label' => 'Intro line', 'type' => 'textarea', 'default' => '{{ actorFullName }} posted a new task. Please review the details below.'],
                    'comment_label' => ['label' => 'Comment label (optional)', 'type' => 'text', 'default' => 'Description'],
                    'cta_label' => ['label' => 'Button label', 'type' => 'text', 'default' => 'View task'],
                    'cta_url' => ['label' => 'Button URL', 'type' => 'text', 'default' => '/dashboard/#details/{{ case_uniq_id }}'],
                    'signoff' => ['label' => 'Sign-off', 'type' => 'signoff', 'default' => 'Thanks &amp; Regards,<br><strong>The {{ companyName }} Team</strong>'],
                    'footer_note' => ['label' => 'Footer note', 'type' => 'textarea', 'default' => "Don't want these emails? Ask your project admin to turn off email notifications for this project."],
                ],
                'tokens' => [
                    'actorName' => ['label' => 'Creator name', 'sample' => 'Jane Doe'],
                    'actorFullName' => ['label' => 'Creator full name', 'sample' => 'Jane Doe'],
                    'actorEmail' => ['label' => 'Creator email', 'sample' => 'jane@example.com'],
                    'recipientName' => ['label' => 'Recipient name', 'sample' => 'John Doe'],
                    'case_title' => ['label' => 'Task title', 'sample' => 'Sample task title'],
                    'case_no' => ['label' => 'Task number', 'sample' => 'TASK-001'],
                    'case_uniq_id' => ['label' => 'Task UUID', 'sample' => '7a1b2c3d-4e5f-6789-abcd-ef0123456789'],
                    'projName' => ['label' => 'Project name', 'sample' => 'Sample Project'],
                    'cseTyp' => ['label' => 'Task type', 'sample' => 'Story'],
                    'priRity' => ['label' => 'Priority (raw HTML allowed)', 'sample' => 'P2 - High', 'raw' => true],
                    'respond' => ['label' => 'Task description (raw HTML allowed)', 'sample' => 'Sample task description.', 'raw' => true],
                    'statusBadge' => ['label' => 'Status badge (raw HTML)', 'sample' => '', 'raw' => true],
                    'attachments' => ['label' => 'Attachments list (raw HTML)', 'sample' => '<a href="#" style="color:#2489B3;">requirements.pdf</a>, <a href="#" style="color:#2489B3;">mockup.png</a>', 'raw' => true],
                    'assignmentLine' => ['label' => 'Assignment line (raw HTML)', 'sample' => '', 'raw' => true],
                    'companyName' => ['label' => 'Company name', 'sample' => 'Orangescrum'],
                ],
                'default_subject' => 'New task: {{ projName }} - {{ case_title }}',
            ],
            'task_assigned' => [
                'label' => 'Task - Assigned',
                'category' => 'Tasks',
                'description' => 'Sent on task assignment.',
                'plugin' => null,
                'shell' => 'task_activity',
                'accent_color' => '#2E7D32',
                'regions' => [
                    'heading' => ['label' => 'Heading', 'type' => 'text', 'default' => 'A task has been assigned to you'],
                    'intro' => ['label' => 'Intro line', 'type' => 'textarea', 'default' => '<strong>{{ actorFullName }}</strong> has assigned a task to you. Please review the details and proceed.'],
                    'comment_label' => ['label' => 'Comment label (optional)', 'type' => 'text', 'default' => 'Note'],
                    'cta_label' => ['label' => 'Button label', 'type' => 'text', 'default' => 'View task'],
                    'cta_url' => ['label' => 'Button URL', 'type' => 'text', 'default' => '/dashboard/#details/{{ case_uniq_id }}'],
                    'signoff' => ['label' => 'Sign-off', 'type' => 'signoff', 'default' => 'Thanks &amp; Regards,<br><strong>The {{ companyName }} Team</strong>'],
                    'footer_note' => ['label' => 'Footer note', 'type' => 'textarea', 'default' => "Don't want these emails? Ask your project admin to turn off email notifications for this project."],
                ],
                'tokens' => [
                    'actorName' => ['label' => 'Assigner name', 'sample' => 'Jane Doe'],
                    'actorFullName' => ['label' => 'Assigner full name', 'sample' => 'Jane Doe'],
                    'actorEmail' => ['label' => 'Assigner email', 'sample' => 'jane@example.com'],
                    'recipientName' => ['label' => 'Assignee name', 'sample' => 'John Doe'],
                    'case_title' => ['label' => 'Task title', 'sample' => 'Sample task title'],
                    'case_no' => ['label' => 'Task number', 'sample' => 'TSK-04-0008'],
                    'case_uniq_id' => ['label' => 'Task UUID', 'sample' => '7a1b2c3d-4e5f-6789-abcd-ef0123456789'],
                    'projName' => ['label' => 'Project name', 'sample' => 'Sample Project'],
                    'cseTyp' => ['label' => 'Task type', 'sample' => 'Story'],
                    'priRity' => ['label' => 'Priority (raw HTML allowed)', 'sample' => 'P2 - High', 'raw' => true],
                    'respond' => ['label' => 'Notes (raw HTML allowed)', 'sample' => 'Please review the requirements and confirm by EOD.', 'raw' => true],
                    'statusBadge' => ['label' => 'Status badge (raw HTML)', 'sample' => '', 'raw' => true],
                    'attachments' => ['label' => 'Attachments list (raw HTML)', 'sample' => '<a href="#" style="color:#2489B3;">requirements.pdf</a>, <a href="#" style="color:#2489B3;">mockup.png</a>', 'raw' => true],
                    'assignmentLine' => ['label' => 'Assignment line (raw HTML)', 'sample' => '', 'raw' => true],
                    'companyName' => ['label' => 'Company name', 'sample' => 'Orangescrum'],
                    'projectName' => ['label' => 'Project display name', 'sample' => 'Sample Project'],
                    'taskTitle' => ['label' => 'Task title / summary', 'sample' => 'Sample task title'],
                    'taskNo' => ['label' => 'Task code', 'sample' => 'TSK-04-0008'],
                    'taskType' => ['label' => 'Task type label', 'sample' => 'Story'],
                    'priorityLabel' => ['label' => 'Priority chip text', 'sample' => 'P2 - High'],
                    'commentBody' => ['label' => 'User-typed comment / note body', 'sample' => '', 'raw' => true],
                    'attachmentsList' => ['label' => 'Rendered list of attachment links', 'sample' => '<a href="#" style="color:#2489B3;">requirements.pdf</a>, <a href="#" style="color:#2489B3;">mockup.png</a>', 'raw' => true],
                    'ctaUrl' => ['label' => 'Primary CTA hyperlink target', 'sample' => 'https://example.com/task/TSK-04-0008'],
                ],
                'default_subject' => 'Task assigned: {{ projectName }} - {{ taskTitle }}',
            ],
            'task_status_change' => [
                'label' => 'Task - Status Change',
                'category' => 'Tasks',
                'description' => 'Sent on task status change (closed, resolved, started, in-progress, etc.).',
                'plugin' => null,
                'shell' => 'task_activity',
                'accent_color' => '#FB8C00',
                'dynamic_accent_token' => 'statusColor',
                'dynamic_accent_region' => 'use_status_color',
                'regions' => [
                    'heading' => ['label' => 'Heading', 'type' => 'text', 'default' => 'Task status updated'],
                    'intro' => ['label' => 'Intro line', 'type' => 'textarea', 'default' => '<strong>{{ actorFullName }}</strong> changed the status of a task you are working on to <strong>{{ statusLabel }}</strong>.'],
                    'comment_label' => ['label' => 'Comment label (optional)', 'type' => 'text', 'default' => 'Note'],
                    'cta_label' => ['label' => 'Button label', 'type' => 'text', 'default' => 'View task'],
                    'cta_url' => ['label' => 'Button URL', 'type' => 'text', 'default' => '/dashboard/#details/{{ case_uniq_id }}'],
                    'use_status_color' => ['label' => 'Use the status color as accent (header, button, link)', 'type' => 'switch', 'default' => '0'],
                    'signoff' => ['label' => 'Sign-off', 'type' => 'signoff', 'default' => 'Thanks &amp; Regards,<br><strong>The {{ companyName }} Team</strong>'],
                    'footer_note' => ['label' => 'Footer note', 'type' => 'textarea', 'default' => "Don't want these emails? Ask your project admin to turn off email notifications for this project."],
                ],
                'tokens' => [
                    'actorName' => ['label' => 'Acting user', 'sample' => 'Jane Doe'],
                    'actorFullName' => ['label' => 'Acting user full name', 'sample' => 'Jane Doe'],
                    'actorEmail' => ['label' => 'Acting user email', 'sample' => 'jane@example.com'],
                    'recipientName' => ['label' => 'Recipient name', 'sample' => 'John Doe'],
                    'case_title' => ['label' => 'Task title', 'sample' => 'Sample task title'],
                    'case_no' => ['label' => 'Task number', 'sample' => 'TSK-04-0008'],
                    'case_uniq_id' => ['label' => 'Task UUID', 'sample' => '7a1b2c3d-4e5f-6789-abcd-ef0123456789'],
                    'projName' => ['label' => 'Project name', 'sample' => 'Sample Project'],
                    'cseTyp' => ['label' => 'Task type', 'sample' => 'Story'],
                    'priRity' => ['label' => 'Priority (raw HTML allowed)', 'sample' => 'P2 - High', 'raw' => true],
                    'respond' => ['label' => 'Status note (raw HTML allowed)', 'sample' => 'Sample status note.', 'raw' => true],
                    'statusBadge' => ['label' => 'Status badge (raw HTML)', 'sample' => '', 'raw' => true],
                    'statusColor' => ['label' => 'Status accent color', 'sample' => '#FB8C00'],
                    'attachments' => ['label' => 'Attachments list (raw HTML)', 'sample' => '<a href="#" style="color:#2489B3;">requirements.pdf</a>, <a href="#" style="color:#2489B3;">mockup.png</a>', 'raw' => true],
                    'assignmentLine' => ['label' => 'Assignment line (raw HTML)', 'sample' => '', 'raw' => true],
                    'companyName' => ['label' => 'Company name', 'sample' => 'Orangescrum'],
                    'projectName' => ['label' => 'Project display name', 'sample' => 'Sample Project'],
                    'taskTitle' => ['label' => 'Task title / summary', 'sample' => 'Sample task title'],
                    'taskNo' => ['label' => 'Task code', 'sample' => 'TSK-04-0008'],
                    'taskType' => ['label' => 'Task type label', 'sample' => 'Story'],
                    'priorityLabel' => ['label' => 'Priority chip text', 'sample' => 'P2 - High'],
                    'statusLabel' => ['label' => 'Status chip text', 'sample' => 'In Progress'],
                    'commentBody' => ['label' => 'User-typed comment / note body', 'sample' => 'Sample status note.', 'raw' => true],
                    'attachmentsList' => ['label' => 'Rendered list of attachment links', 'sample' => '<a href="#" style="color:#2489B3;">requirements.pdf</a>, <a href="#" style="color:#2489B3;">mockup.png</a>', 'raw' => true],
                    'ctaUrl' => ['label' => 'Primary CTA hyperlink target', 'sample' => 'https://example.com/task/TSK-04-0008'],
                ],
                'default_subject' => 'Status changed on {{ projectName }} - {{ taskTitle }}',
            ],
            'task_actions' => [
                'label' => 'Task - Actions',
                'category' => 'Tasks',
                'description' => 'Sent when a task property changes (priority, due date, type, estimated hours, progress, title, story point, file removed, approval, approver, description, etc.).',
                'plugin' => null,
                'shell' => 'task_activity',
                'accent_color' => '#55A0C7',
                'regions' => [
                    'heading' => ['label' => 'Heading', 'type' => 'text', 'default' => 'Task updated'],
                    'intro' => ['label' => 'Intro line', 'type' => 'textarea', 'default' => '{{ actorFullName }} updated a task you are working on.'],
                    'comment_label' => ['label' => 'Comment label (optional)', 'type' => 'text', 'default' => ''],
                    'cta_label' => ['label' => 'Button label', 'type' => 'text', 'default' => 'View task'],
                    'cta_url' => ['label' => 'Button URL', 'type' => 'text', 'default' => '/dashboard/#details/{{ case_uniq_id }}'],
                    'signoff' => ['label' => 'Sign-off', 'type' => 'signoff', 'default' => 'Thanks &amp; Regards,<br><strong>The {{ companyName }} Team</strong>'],
                    'footer_note' => ['label' => 'Footer note', 'type' => 'textarea', 'default' => "Don't want these emails? Ask your project admin to turn off email notifications for this project."],
                ],
                'tokens' => [
                    'actorName' => ['label' => 'Acting user', 'sample' => 'Jane Doe'],
                    'actorFullName' => ['label' => 'Acting user full name', 'sample' => 'Jane Doe'],
                    'actorEmail' => ['label' => 'Acting user email', 'sample' => 'jane@example.com'],
                    'recipientName' => ['label' => 'Recipient name', 'sample' => 'John Doe'],
                    'case_title' => ['label' => 'Task title', 'sample' => 'Sample task title'],
                    'case_no' => ['label' => 'Task number', 'sample' => 'TASK-001'],
                    'case_uniq_id' => ['label' => 'Task UUID', 'sample' => '7a1b2c3d-4e5f-6789-abcd-ef0123456789'],
                    'projName' => ['label' => 'Project name', 'sample' => 'Sample Project'],
                    'cseTyp' => ['label' => 'Task type', 'sample' => 'Story'],
                    'priRity' => ['label' => 'Priority (raw HTML allowed)', 'sample' => 'P2 - High', 'raw' => true],
                    'respond' => ['label' => 'Action note (raw HTML allowed)', 'sample' => 'Updated priority to High.', 'raw' => true],
                    'statusBadge' => ['label' => 'Status badge (raw HTML)', 'sample' => '', 'raw' => true],
                    'attachments' => ['label' => 'Attachments list (raw HTML)', 'sample' => '<a href="#" style="color:#2489B3;">requirements.pdf</a>, <a href="#" style="color:#2489B3;">mockup.png</a>', 'raw' => true],
                    'assignmentLine' => ['label' => 'Assignment line (raw HTML)', 'sample' => '', 'raw' => true],
                    'companyName' => ['label' => 'Company name', 'sample' => 'Orangescrum'],
                ],
                'default_subject' => 'Update on {{ projName }} - {{ case_title }}',
            ],

        ],
    ],
];
