DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT table_schema, table_name, column_name
        FROM information_schema.columns
        WHERE column_name = 'id'
          AND is_identity = 'YES'
          AND identity_generation = 'ALWAYS'
          AND table_schema = 'public'
    LOOP
        EXECUTE format(
            'ALTER TABLE %I.%I ALTER COLUMN %I SET GENERATED BY DEFAULT',
            r.table_schema, r.table_name, r.column_name
        );
    END LOOP;
END;
$$;






